services:
  test-runner:
    image: node:22-alpine
    working_dir: /tests
    depends_on:
      - ai-gateway
    environment:
      - API_BASE=http://ai-gateway:8080
    volumes:
      - ./ai-gateway/tests:/tests:ro
    command: ["/bin/sh","-lc","apk add --no-cache ffmpeg && ffmpeg -f lavfi -i color=c=black:s=320x240:d=1 -pix_fmt yuv420p /tmp/sample.mp4 -y && TEST_VIDEO=/tmp/sample.mp4 node integration.mjs"]

