name: CI

on:
  push:
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # Pass repository secrets to all docker compose commands securely
    env:
      OPENROUTER_API_KEYS: ${{ secrets.OPENROUTER_API_KEYS }}
      OPENROUTER_MODEL: ${{ secrets.OPENROUTER_MODEL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show Docker and Compose versions
        run: |
          docker --version
          docker compose version

      - name: Build and start services
        run: |
          docker compose up -d --build

      # Sanity-check: ensure ai-gateway can see the env (prints only 'present/missing')
      - name: Verify ai-gateway env injection (non-secret)
        run: |
          docker compose run --rm ai-gateway node -e "console.log(process.env.OPENROUTER_API_KEYS ? 'present' : 'missing', process.env.OPENROUTER_MODEL ? 'present' : 'missing')"

      - name: Python unit tests (video-processor)
        run: |
          docker compose run --rm video-processor pytest -q

      - name: Node unit tests (ai-gateway)
        run: |
          docker compose run --rm ai-gateway npm test

      - name: Integration test (upload → frames → results)
        run: |
          docker compose -f docker-compose.yml -f docker-compose.test.yml run --rm test-runner

      - name: Lint frontend
        run: |
          docker compose run --rm frontend npm run lint

      - name: Lint ai-gateway
        run: |
          docker compose run --rm ai-gateway npm run lint

      - name: Python formatting check (black)
        run: |
          docker compose run --rm video-processor black --check .

