name: CI

on:
  push:
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # Pass repository secrets to all docker compose commands securely
    env:
      OPENROUTER_API_KEYS: ${{ secrets.OPENROUTER_API_KEYS }}
      OPENROUTER_MODEL: ${{ secrets.OPENROUTER_MODEL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show Docker and Compose versions
        run: |
          docker --version
          docker compose version

      - name: Build and start services (CI override without host ports)
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d --build


      - name: Python unit tests (video-processor) with coverage gate
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm video-processor pytest -q --cov=. --cov-fail-under=60

      - name: Node unit tests (ai-gateway) with coverage
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm ai-gateway npm run test:coverage

      - name: Frontend unit tests with coverage
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm frontend npm run test:coverage

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            ai-gateway/coverage
            frontend/coverage

      - name: Integration test (upload → frames → results)
        run: |
          docker compose -f docker-compose.yml -f docker-compose.test.yml -f docker-compose.ci.yml run --rm test-runner

      - name: Lint frontend
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm frontend npm run lint

      - name: Lint ai-gateway
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm ai-gateway npm run lint

      - name: Python formatting check (black)
        run: |
          docker compose run --rm video-processor black --check . || (docker compose run --rm video-processor black --diff .; exit 1)

